# Generated by Django 2.1.2 on 2018-11-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='blog_post',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
