# Generated by Django 2.1.2 on 2018-11-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
